name: Deploy App to EC2

on:
  push:
    branches:
      - main  # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build & Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
            -f Backend-master/Dockerfile ./Backend-master
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # 5️⃣ Build & Push Frontend Docker Image
      
      - name: Build and Push Frontend Docker Image
        run: |
          docker build --build-arg NEXT_PUBLIC_DISABLE_ESLINT=true \
            --build-arg CI=false \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest \
            -f frontend-main/Dockerfile ./frontend-main
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # 6️⃣ Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull updated images from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            # Stop and remove existing containers
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            # Run Prisma Migrations before starting the backend
            docker run --rm \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest \
              npx prisma migrate deploy

            # Start Backend Container (Use `npm run dev`)
            docker run -d --name backend -p 4000:4000 --restart always \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest \
              npm run dev

            # Start Frontend Container
            docker run -d --name frontend -p 3000:3000 --restart always \
              ${{ secrets.DOCKER_USERNAME }}/frontend:latest \
              npm run dev
