name: Deploy App to EC2

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
            -f Backend-master/Dockerfile ./Backend-master
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Build & Push Frontend Docker Image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f frontend-main/Dockerfile ./frontend-main
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true
            docker run -d --name backend -p 4000:4000 --restart always \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest
            docker run -d --name frontend -p 3000:3000 --restart always ${{ secrets.DOCKER_USERNAME }}/frontend:latest
